---
- name: Deploy Spring Boot application
  hosts: azure_servers
  become: true

  tasks:
  - name: Ensure Java is installed
    ansible.builtin.package:
      name: java-11-openjdk
      state: present

  - name: Copy Spring Boot application JAR
    ansible.builtin.copy:
      src: target/app.jar
      dest: /home/hamza/application.jar

  - name: Run Spring Boot application
    ansible.builtin.shell:
      cmd: nohup java -jar /home/hamza/application.jar > /dev/null 2>&1 &
